version: '3.8'

services:
  api:
    build: .
    container_name: masanteplus_api
    restart: always
    ports:
      - "3333:3333"
    env_file: .env
    depends_on:
      - db
    networks:
      - masanteplus_network

  db:
    image: postgres:16
    container_name: masanteplus_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: masanteplus
    ports:
      - "5437:5432"   # ðŸ”¥ accÃ¨s Ã  la base depuis lâ€™extÃ©rieur (ex: pgAdmin)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - masanteplus_network

volumes:
  postgres_data:

networks:
  masanteplus_network:
