version: "3.8"
services:
  masanteplus_db:
    image: postgres:16
    container_name: masanteplus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: masanteplus
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - masanteplus_network

  adonis_api:
    build: .
    container_name: adonis_api
    ports:
      - "3333:3333"
    env_file:
      - .env       # <-- on lie le fichier externe
    depends_on:
      - masanteplus_db
    networks:
      - masanteplus_network

networks:
  masanteplus_network:
    driver: bridge

volumes:
  pgdata:


